'1: 'Route: v1'':
- changed-files:
  - any-glob-to-any-file: ['lib/router.js']
  - all-globs-to-any-file: ['lib/routes/**/*.js', '!lib/routes/index.js']

'3: 'Route: v2'':
- changed-files:
  - any-glob-to-any-file: ['lib/v2/**/*.js']

5: core enhancement:
- changed-files:
  - any-glob-to-any-file: ['lib/routes/index.js']
  - all-globs-to-any-file: ['lib/**', '!lib/radar-rules.js', '!/lib/config.js', '!lib/router.js', '!lib/routes/**', '!lib/v2/**']

7: dependencies:
- changed-files:
  - any-glob-to-any-file: ['package.json', 'pnpm-lock.yaml', 'yarn.lock']
