version: '3'
services:
  rsshub:
    image: diygod/rsshub
    ports:
      - '1200:1200'
    volumes:
      - redis-data:/data
    environment:
      - CACHE_EXPIRE=3600
    depends_on:
      - redis

  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
