version: '3'
services:
  rsshub:
    image: diygod/rsshub
    ports:
      - '1200:1200'
    environment:
      - REDIS_URL=redis://localhost:6379
    volumes:
      - redis-data:/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  redis-data:
