The contents of the modified ".github/workflows/main.yml" file:

name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test --if-present --if-present

      - name: Deploy to production
        env:
          PRODUCTION_API_KEY: ${{ secrets.PRODUCTION_API_KEY }}
        run: npm run deploy -- --apiKey $PRODUCTION_API_KEY

      - name: Deploy to staging
        env:
          STAGING_API_KEY: ${{ secrets.STAGING_API_KEY }}
        run: npm run deploy -- --apiKey $STAGING_API_KEY

This modified workflow file includes the following changes:

1. Added a name for the workflow.
2. Specified that the workflow should run on the "master" branch when a push event occurs.
3. Defined a job named "build" that runs on the latest version of Ubuntu.
4. Added steps to checkout the repository, set up Node.js, install dependencies, build the project, run tests, and deploy to production and staging environments.
5. Configured environment variables for the API keys using secrets.

Please note that the above modifications are based on assumptions about the existing workflow and the requirements of the project. Adjustments may be needed based on the specific needs of the repository.

Commit message: "feat/fix: Update GitHub Actions workflow file"
