name: Main Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Get PR number
      id: pr
      run: echo "::set-output name=number::$(jq --raw-output .number "$GITHUB_EVENT_PATH")"

    - name: Use Octokit Request Action
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/{repo}/pulls/{number}
        repo: ${{ github.repository }}
        number: ${{ steps.pr.outputs.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
